const twilio = require('twilio')
const client = twilio(process.env.TWILIO_ACCOUNT_SID, process.env.TWILIO_AUTH_TOKEN)

async function sendEmergencySMS(contact, alert, user) {
  const locationStr = alert.location?.address ||
    (alert.location?.lat ? `${alert.location.lat.toFixed(4)}, ${alert.location.lng.toFixed(4)}` : 'Unknown location')

  const googleMapsUrl = alert.location?.lat
    ? `https://maps.google.com/?q=${alert.location.lat},${alert.location.lng}`
    : ''

  const message =
    `🚨 SHEild EMERGENCY ALERT\n` +
    `${user.name} has triggered a Level ${alert.level} alert.\n` +
    `📍 Location: ${locationStr}\n` +
    (googleMapsUrl ? `🗺️ Map: ${googleMapsUrl}\n` : '') +
    `⏰ Time: ${new Date().toLocaleString()}\n` +
    `⚡ Trigger: ${alert.triggerType}\n` +
    `This is an automated alert from SHEild Safety App. Please check on them immediately.`

  try {
    await client.messages.create({
      body: message,
      from: process.env.TWILIO_PHONE_NUMBER,
      to: contact.phone
    })
    console.log(`✅ SMS sent to ${contact.phone}`)
    return true
  } catch (err) {
    console.error(`❌ Twilio SMS error to ${contact.phone}:`, err.message)
    return false
  }
}

async function makeEmergencyCall(contact, user) {
  try {
    await client.calls.create({
      twiml: `<Response><Say voice="alice">
        This is an emergency alert from SHEild Safety App.
        ${user.name} has triggered an emergency. Please check on them immediately.
        This call was automatically generated by SHEild.
      </Say></Response>`,
      from: process.env.TWILIO_PHONE_NUMBER,
      to: contact.phone
    })
    console.log(`✅ Emergency call placed to ${contact.phone}`)
    return true
  } catch (err) {
    console.error(`❌ Twilio call error:`, err.message)
    return false
  }
}

module.exports = { sendEmergencySMS, makeEmergencyCall }
